### ISSUE TITLE
Bevel Gear Placement - cone height calculation?

### ISSUE THREAD

**Issue by gumyr** [meadiode/cq_gears#12]
Thanks for adding assemblies - very handy. 

Currently I'm building a bevel gear pair where I need to modify the gears (add a bearing to the pinion and a hub to the gear) so I used BevelGear and tried to build my own assembly and compare it to BevelGearPair.  Unfortunately, I can't place them to match the gear pair.  Here is some test code:

```python
import cadquery as cq
from cq_gears import BevelGear, BevelGearPair

gear_pair = BevelGearPair(module=2, gear_teeth=30, pinion_teeth=12, face_width=10)
gear_pair_assembly = gear_pair.assemble()

gear = BevelGear(module=2, teeth_number=30, cone_angle=65, face_width=10)
gear_object = gear.build()
pinion = BevelGear(module=2, teeth_number=12, cone_angle=25, face_width=10)
pinion_object = (
    pinion.build()
    .rotate(cq.Vector(), cq.Vector(0, 1, 0), 90)
    .translate(cq.Vector(-pinion.cone_h, 0, gear.cone_h))
)
show_object(gear_pair_assembly, name="gear_pair_assembly")
show_object(gear_object, name="gear_object")
show_object(pinion_object, name="pinion_object")
```
![image](https://user-images.githubusercontent.com/85638518/162826437-946eba7a-6865-4288-b18d-840cb9e02e1d.png)

If I've understood how the gear pair works, the cone heights should be all I need to place them correctly (ignoring gear rotation) but the pinion isn't in the correct location.  Is there something I'm doing wrong?

**Comment by meadiode** [comment]
Hi,
The problem is that your gear and pinion are not the same as in gear_pair.

Cone angles should be slightly different, they are actually dependent on gear/pinion ratio and they cannot be arbitrary values, sum of which gives 90 (or any other desired axis angle). 

Basically, you can calculate the angle for the pinion using the following formula:
```
pinion_cone_angle = atan(pinion.z / gear.z)
```
and for the gear:
```
gear_cone_angle = 90 - pinion_cone_angle
```
In this case, with given number of teeth, cone angles are going to be 21.8 and 68.2.

I tried the following and it worked fine (if you ignore gear rotation):
```python
import cadquery as cq
from cq_gears import BevelGear, BevelGearPair
from math import atan, degrees

gear_pair = BevelGearPair(module=2, gear_teeth=30, pinion_teeth=12, face_width=10)
gear_pair_assembly = gear_pair.assemble()

pinion_cone_angle = degrees(atan(12 / 30))
gear_cone_angle = 90 - pinion_cone_angle

gear = BevelGear(module=2, teeth_number=30, cone_angle=gear_cone_angle, face_width=10)
gear_object = gear.build()
pinion = BevelGear(module=2, teeth_number=12, cone_angle=pinion_cone_angle, face_width=10)
pinion_object = (
    pinion.build()
    .rotate(cq.Vector(), cq.Vector(0, 1, 0), 90)
    .translate(cq.Vector(-pinion.cone_h, 0, gear.cone_h))
)
show_object(gear_pair_assembly, name="gear_pair_assembly")
show_object(gear_object, name="gear_object")
show_object(pinion_object, name="pinion_object")
```

**Comment by gumyr** [comment]
Thank you!  I was under the mistaken impression that the cone angles just needed to add up to the shaft angle and unfortunately got kind'a close to the right answer. It would be great if you added a method to calculate these angles, something like:
```python
(pinion_cone_angle, gear_cone_angle) = BevelGear.calculate_cone_angles(shaft_angle, gear_teeth, pinion_teeth)
```
so that my mistake is less likely to be repeated in the future.

Thanks for your great work.

**Comment by meadiode** [comment]
@gumyr You are welcome!

Btw, you can take pinion and gear objects from the gear_pair instance like so:
```python
gear_object = gear_pair.gear.build()
pinion_object = gear_pair.pinion.build()
...
```
So you don't have to calculate the cone angles for both of them, as it's already done inside gear_pair.

**Comment by gumyr** [comment]
Very nice.  My pinion code is as follows now:
class DifferentialPinion:

bearing = SingleRowCappedDeepGrooveBallBearing(size="M4-11-4", bearing_type=
"SKT")
pinion = DifferentialGearPair.bevel_pair.pinion

@property
def cq_object(self):
return self.pinion_gear_assembly

def __init__(
self,
clearance: float = 0.2 * MM,
):
self.clearance = clearance

self.pinion_gear_assembly = Assembly(None)
self.pinion_gear = (
Workplane("XY")
# Create bevel pinion
.gear(self.pinion)
.rotate((0, 0, 0), (0, 0, 1), 180 / self.pinion.z)
# On the back
.faces("<Z")
.workplane()
# Press fit a bearing
.pressFitHole(
bearing=self.bearing,
interference=-self.clearance / 2,
baseAssembly=self.pinion_gear_assembly,
)
)
self.pinion_gear_assembly.add(self.pinion_gear, color=cq.Color("goldenrod"))
Which I use to create:
[image: image.png]
where the pinions have small bearings in them (which are themselves an
assembly) and the gears have a hub with a heatsert nut and set screw to
lock down the key.

I didn't see a way to replace the generic gear and pinion in the
BevelGearPair.assembly() with my modified ones without creating them twice
- is there a way?  One possible solution is to change the assemble() method
to something like this:
def assemble(
self,
gear=None,
pinion=None,
transform_pinion=True,
gear_build_args={},
pinion_build_args={},
**kv_args,
):
and build the gear and/or pinion if none are provided.

By the way, I couldn't find an instance variable for the outer diameter of
a gear which I use to build the differential case.  I'm using a bounding
box which is fine but having the data available would be great.

Thanks again,
Roger

**Comment by meadiode** [comment]
Hi Roger,

> I didn't see a way to replace the generic gear and pinion in the
> BevelGearPair.assembly() with my modified ones without creating them twice
> - is there a way?

I think you can create a new class based on BevelGear and redefine method .build, then create a new class based on BevelGearPair and assign your class to the .gear_cls class member.

Here is a quick example:

```python
class MyBevelGear(BevelGear):
    
    def build(self, square_bore=7.0, **kv_args):
        body = super(MyBevelGear, self).build(**kv_args)
        
        # Here you could add whatever modifications to the gear's body - add hub, set screw etc.
        
        body = (cq.Workplane('XY')
                .add(body)
                .rect(square_bore, square_bore)
                .cutThruAll())
        
        return body
    
    
class MyBevelGearPair(BevelGearPair):
    gear_cls = MyBevelGear
    

gear_pair = MyBevelGearPair(module=2, gear_teeth=30, pinion_teeth=12, face_width=10)
gear_pair_assembly = gear_pair.assemble()

```

> By the way, I couldn't find an instance variable for the outer diameter of
> a gear which I use to build the differential case.  I'm using a bounding
> box which is fine but having the data available would be great.

Yeah, there's no such variable for the outer diameter, I should add it.
